### ISSUE TITLE
Author and Date in Cover are no aligned

### ISSUE THREAD

**Issue by Ye-Jinhong** [alexanderdavide/slidev-theme-academic#10]
When use [default code](https://github.com/alexanderdavide/slidev-theme-academic/blob/149190f10aafa874ba9509cfc2c7673f3db28f13/example.md), I can't get the layout as [shown picture](https://github.com/alexanderdavide/slidev-theme-academic/blob/89b5422490b6af3d3a8518d0321bc2c20e2622af/example-export/01.png). But I have the following layout:
![image](https://user-images.githubusercontent.com/48616668/223309513-2a6c6b1d-1184-4f70-8cb3-c8ff6b379a73.png)

The left bottom corner where author and date are placed is not aligned with title.

Code:
```markdown
---
theme: academic
layout: cover
coverAuthor: alexanderdavide
coverAuthorUrl: https://www.alexeble.de
fonts:
  local: Montserrat, Roboto Mono, Roboto Slab 
themeConfig:
  paginationX: r
  paginationY: t
  paginationPagesDisabled: [1]
title: slidev-theme-academic

---

# Welcome to Slidev

Presentation slides for developers
---
```

Environment:
- Windows 11
- Slidev  v0.40.3

**Comment by alexanderdavide** [comment]
Hi, thanks for using slidev-theme-academic and reporting this bug!

I can readily reproduce it on @slidev/cli v0.40.3 while it wasn't a problem in earlier version e. g. v0.35.6.

I'll try to fix this in the next days.

**Comment by alexanderdavide** [comment]
This should be fixed in the latest release [v.1.1.2](https://github.com/alexanderdavide/slidev-theme-academic/releases/tag/1.1.2).

**Comment by Ye-Jinhong** [comment]
Thanks for much, there is no problem after updating. By the way, this theme is succinct and beautiful.

**Comment by alexanderdavide** [comment]
So happy to hear that. Thanks a lot!
