### ISSUE TITLE
Error with images paths when uploading to GitHub pages

### ISSUE THREAD

**Issue by george-gca** [alexanderdavide/slidev-theme-academic#14]
I am having problems with the layouts introduced in this theme. When referring to images in slidev, I have been using them like this:

```html
<img src="/images/sisr/ankle1.png" />
```

which generates the following underlying url:

```html
<img src="/bracis_2023_srcaps/assets/ankle1-de1cf3b3.png">
```

This way it correctly displays both locally in dev and in GitHub pages. But when using with the layouts introduced in the template, they paths are not generated correctly. By using something like:

```
---
hideInToc: true
layout: figure
figureCaption: Test
figureFootnoteNumber: 1
figureUrl: /images/questions.jpg
---
```

it is generating the following url:

```html
<img alt="Test" class="max-h-full" src="/bracis_2023_srcapsimages/questions.jpg">
```

which is wrong.

---

This can be seen in my repo, by checking [the directory with the images](https://github.com/george-gca/bracis_2023_srcaps/tree/main/images/cover) and my [cover slide](https://github.com/george-gca/bracis_2023_srcaps/blob/main/slides.md). Only the background image, that is handled by the theme, is [not shown](https://george-gca.github.io/bracis_2023_srcaps/). The same happens with the last slide.

**Comment by george-gca** [comment]
Ok I just found out in slidev docs that I should put my assets in the [public/](https://github.com/slidevjs/slidev/discussions/180) dir. That fixed it, but still it is weird that the previous path worked with img and not with the layouts from this theme.

**Comment by george-gca** [comment]
Actually it is still generating it with a missing `/` at the beginning. It still keeps generating it like:

```html
<img alt="Test" class="max-h-full" src="/bracis_2023_srcapsimages/questions.jpg">
```

The difference now is that the image is in the correct path `/bracis_2023_srcaps/images/questions.jpg`, but the leading `/` is missing in the generated path.

**Comment by george-gca** [comment]
Do you have any idea how to solve this @alexanderdavide?

**Comment by alexanderdavide** [comment]
Hey @george-gca, sorry for the delay. It's hard for me to find the time.

What's the exact base URL your app is being served from? Have a look at [layout-helper.ts](https://github.com/alexanderdavide/slidev-theme-academic/blob/master/layout-helper.ts) which resolves the URLs your passing to the theme–actually I've simply adopted this from slidev's [layoutHelper.ts](https://github.com/slidevjs/slidev/blob/main/packages/client/layoutHelper.ts) source. `resolveAssetUrl` slices the leading slash off your URLs assuming your base URL includes a trailing slash. If the latter isn't true, there is no slash at all and the URL is going to be wrong. I admit, this is quite error-prone and could be more elaborate.

**Comment by george-gca** [comment]
After your explanation I was able to create a fix for this, but the issue still persists in some places. For instance it solved for the 1st slide BG, but not when I call some images. Is there any other place that the path to the assets are changed like this?

**Comment by george-gca** [comment]
For some unknown reason the function `resolveAssetUrl` is not being called inside [FigureWithOptionalCaption.vue](https://github.com/alexanderdavide/slidev-theme-academic/blob/master/components/FigureWithOptionalCaption.vue). Take a look at [my slides](https://george-gca.github.io/bracis_2023_srcaps/26) and press F12. I changed the function inside [layout-helper.ts](https://github.com/george-gca/bracis_2023_srcaps/blob/main/layout-helper.ts) to the one I changed in the draft PR. If you look at the console in the browser, it only prints the path to the background image, not to the image in the questions slide. But if you change the path manually in the html adding the missing `/` before `images` it displays correctly.

That slide is the last one in [slides.md](https://raw.githubusercontent.com/george-gca/bracis_2023_srcaps/main/slides.md).

**Comment by alexanderdavide** [comment]
Hey @george-gca,

in george-gca/bracis_2023_srcaps you're using a local `cover` layout which imports `handleBackground()` from your customized layout-helper.ts file. Meanwhile, `FigureWithOptionalCaption` still roots in slidev-theme-academic and hence uses the flawed, packaged `resolveAssetUrl()`. To verify, try copying `FigureWithOptionalCaption` over to george-gca/bracis_2023_srcaps too.

**Comment by george-gca** [comment]
Ok it makes sense.

**Comment by george-gca** [comment]
Another thing, I just realized that there was one simple difference from my solution and slidev docs, namely this:

```yaml
run: npm run build -- --base /<name_of_repo>/
```

while mine was without the `/`s

```yaml
run: npm run build -- --base <name_of_repo>
```

this was the main problem. But I believe their solution should be more robust to differences like this one.
