### ISSUE TITLE
Create cover slide with more authors

### ISSUE THREAD

**Issue by george-gca** [alexanderdavide/slidev-theme-academic#16]
First of all, I love this theme. It is really well thought.

One thing I was missing though, is to be able to add more authors, each with its own url. In my case I created a copy of the cover layout and manually added the needed structure, but maybe an option could be part of the theme itself.

One suggestion would be to have only 1 variable, as it currently is, but when creating the cover page split the values by commas, and then displaying them individually. What do you think?

**Comment by alexanderdavide** [comment]
Hey George,

thanks a lot for your suggestions and the kind words. This makes working on it a lot more fun!

I totally understand your point. After thinking about it, I'm not sure about the following aspects:
* The date may get lost visually when the line becomes longer with multiple authors. Should it move somewhere else?
* As you say, we could leave the variables as they are and expect comma separation if there are multiple values. Another approach would be to pluralize the variables and make them arrays of strings. Or, we could even have one single variable as an array of objects with name and URL keys. Your solution has the advantage of being backward compatible. Changing the variables, however, would be more explicit and reliable but would introduce a breaking change.

What do you think?

**Comment by george-gca** [comment]
In this specific case I would vote for the breaking change, as it would make things more explicit. I like the idea of creating an array of objects, with name and url as keys. That way would allow for even more possible customizations in the future. For example, suppose one would want to add an image per author. This way this information could be readily available as a new `key: value` pair in the already available list of authors.

As for the date location, maybe it could be a position variable, like the one already used for the pagination position. Also, having more authors would mean to decrease authors font size, inserting line breaks, or even decrease the title font size to accommodate the authors names. In my case I just changed my title to `##` instead of `#`.

**Comment by alexanderdavide** [comment]
You're right, an object is indeed more flexible for further adaptations. In a 2.0.0 release, I'd definitely consider this. However, currently this would be the only change requiring another major version. As for now, I'm thinking about quickly implementing the discussed solution based on delimiters within the existing variable.

I know what you mean but I'm not really into making it this complex. I mean, a lot of texts in Slidev don't scale appropriately when getting to long. Folks with edge cases still have the opportunity of leaving out author and date to add their own markup. Consequently, I'm pondering a different position of the date or leave it as it is.

**Comment by alexanderdavide** [comment]
For now I'll leave this here as an issue labelled with enhancement.

I plan to implement and release this over the holidays.

**Comment by alexanderdavide** [comment]
In #20 I've added the possibility to pass arrays to `coverAuthor` and `coverAuthorUrl`, of course while keeping the current API intact. I found arrays to be more explicit than working with a delimited string.

In a next major release, I still consider harmonizing this to a unified variable as an array of objects. I'll add a separate issue after finishing this one here.
